server:
  port: 8888

spring:
  profiles:
    active: dev  #切换运行环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  rabbitmq:
    port: 5672
  messages:
    basename: i18n/messages
  thymeleaf:
    cache: false
  quartz:
    job-store-type: jdbc
  mail:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.requried: true

logging:
  config: classpath:log4j2.yml

mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: id_worker
  type-enums-package: com.yupaits.commons.consts.enums

api:
  version: ${spring.profiles.active} v1.0.0
  contact-name: YupaiTS
  contact-url: https://github.com/YupaiTS
  contact-email: ts495606653@hotmail.com
  termsOfServiceUrl:
  license: Apache v2 License
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  groups:
  - name: auth
    title: Auth模块接口
    description: 权限模块接口文档
  - name: sys
    title: 系统管理接口
    description: 系统管理接口文档
  - name: message
    title: 消息中心接口
    description: 消息中心接口文档
  - name: schedule
    title: 定时任务接口
    description: 定时任务管理接口文档

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: sql123
  redis:
    host: localhost
    port: 6379
    password:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    port: 25
    username: xxxxxxxxx@qq.com
    password: xxxxxxxx
    test-connection: false

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:
    - 127.0.0.1:22122

upload:
  temp-dir: /tmp/upload/
  watermark: /watermark.jpg
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: sql123
  redis:
    host: localhost
    port: 6379
    password:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  mail:
    host: smtp.qq.com
    port: 25
    username: xxxxxxxxx@qq.com
    password: xxxxxxxx
    test-connection: false

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:
    - 127.0.0.1:22122

upload:
  temp-dir: /tmp/upload/
  watermark: /watermark.jpg
---