server:
  port: 8888

mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-enums-package: com.yupaits.commons.consts.enums

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sql123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8